In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
here = os.getcwd()
dataSet = pd.read_csv(os.path.join(here,"..","dataset","data.csv"), sep=";")

In [13]:
data = np.array(dataSet)
colunas = dataSet.columns.to_list()

In [21]:
data[0]

array([1, 17, 5, 171, 1, 1, 122.0, 1, 19, 12, 5, 9, 127.3, 1, 0, 0, 1, 1,
       0, 20, 0, 0, 0, 0, 0, 0.0, 0, 0, 0, 0, 0, 0.0, 0, 10.8, 1.4, 1.74,
       'Dropout'], dtype=object)

In [52]:
dropout = dataSet.loc[
                    dataSet["Target"] == "Dropout",
                    colunas[0:21]+colunas[33:36]
]
graduate = dataSet.loc[
                    dataSet["Target"] == "Graduate",
                    colunas[0:27]+colunas[33:36]
]
enrolled = dataSet.loc[
                    dataSet["Target"] == "Enrolled",
                    colunas[0:36]
]

In [56]:
dropout.to_csv(os.path.join(here,"..","dataset","dropout.csv"), sep=";", index=False)

In [57]:
graduate.to_csv(os.path.join(here,"..","dataset","graduate.csv"), sep=";", index=False)

In [58]:
enrolled.to_csv(os.path.join(here,"..","dataset","enrolled.csv"), sep=";", index=False)

In [60]:
dropout

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,International,Unemployment rate,Inflation rate,GDP
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,1,1,0,20,0,10.8,1.4,1.74
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,0,0,1,0,19,0,10.8,1.4,1.74
7,1,18,4,9254,1,1,119.0,1,37,37,...,0,0,0,1,0,22,0,15.5,2.8,-4.06
9,1,1,1,9238,1,1,138.0,1,1,19,...,0,1,0,0,0,18,0,8.9,1.4,3.51
12,1,1,2,9853,1,1,133.0,1,19,37,...,0,0,1,0,0,19,0,12.7,3.7,-1.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4408,2,39,1,9773,1,1,100.0,1,37,37,...,0,0,1,1,0,47,0,12.7,3.7,-1.70
4411,1,44,1,9130,1,39,150.0,1,37,37,...,0,0,1,1,0,21,0,13.9,-0.3,0.79
4415,4,39,1,9500,1,19,133.1,1,37,37,...,0,1,0,0,0,46,0,11.1,0.6,2.02
4420,1,1,2,9773,1,1,120.0,105,1,1,...,0,1,0,0,0,18,1,11.1,0.6,2.02
4421,1,1,1,9500,1,1,154.0,1,37,37,...,0,0,1,0,1,30,0,13.9,-0.3,0.79

In [61]:
graduate

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,International,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Unemployment rate,Inflation rate,GDP
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,0,6,6,6,14.000000,0,13.9,-0.3,0.79
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,0,6,8,6,13.428571,0,9.4,-0.8,-3.12
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,0,6,9,5,12.333333,0,13.9,-0.3,0.79
5,2,39,1,9991,0,19,133.1,1,37,37,...,0,0,5,10,5,11.857143,0,16.2,0.3,-0.92
6,1,1,1,9500,1,1,142.0,1,19,38,...,0,0,7,9,7,13.300000,0,15.5,2.8,-4.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4417,1,1,1,9070,1,1,132.0,1,1,1,...,0,0,6,6,6,13.833333,0,16.2,0.3,-0.92
4418,1,44,1,9070,1,39,120.0,1,3,38,...,0,2,7,7,6,12.500000,0,16.2,0.3,-0.92
4419,1,1,6,9773,1,1,125.0,1,1,1,...,0,0,6,7,5,13.600000,0,15.5,2.8,-4.06
4422,1,1,1,9147,1,1,180.0,1,37,37,...,0,0,5,5,5,13.800000,0,9.4,-0.8,-3.12
4423,1,10,1,9773,1,1,152.0,22,38,37,...,1,0,6,8,6,11.666667,0,12.7,3.7,-1.70

In [62]:
enrolled

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
16,1,18,1,9238,1,1,137.0,1,19,38,...,0,0,6,14,2,11.000000,0,10.8,1.4,1.74
19,1,1,1,9853,1,1,140.0,1,19,19,...,0,0,7,8,6,13.500000,0,16.2,0.3,-0.92
21,1,18,4,9556,1,1,127.0,1,1,38,...,0,0,8,9,8,11425.000000,0,12.7,3.7,-1.70
25,1,1,1,9238,1,1,151.0,1,19,38,...,0,0,6,12,4,11.000000,0,7.6,2.6,0.32
27,1,1,1,9085,1,1,138.0,1,19,19,...,2,0,5,7,4,13.000000,0,9.4,-0.8,-3.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4397,1,5,4,9853,1,1,116.0,1,3,38,...,0,0,6,9,3,11.666667,0,9.4,-0.8,-3.12
4402,1,18,2,9853,1,1,168.0,1,1,19,...,0,0,6,6,6,13.000000,0,10.8,1.4,1.74
4406,1,1,1,9070,1,1,145.0,1,1,38,...,0,0,6,8,2,11.333333,0,10.8,1.4,1.74
4412,1,43,1,9070,1,1,125.0,1,19,19,...,0,2,6,7,5,12.200000,0,13.9,-0.3,0.79
4413,1,43,1,33,1,1,143.0,1,37,1,...,0,2,8,10,2,13.000000,0,12.4,0.5,1.79